package com.bodik.calories.entities.product

import com.bodik.calories.entities.Product

fun getInitialProducts(): List<Product> {
    return listOf(
        Product(id = "1", title = "Апельсин, мандарин", calories = 47, isFavorites = false),
        Product(id = "2", title = "Банан", calories = 90, isFavorites = false),
        Product(id = "3", title = "Виноград", calories = 78, isFavorites = false),
        Product(id = "4", title = "Груша", calories = 57, isFavorites = false),
        Product(id = "5", title = "Инжир сушеный", calories = 260, isFavorites = false),
        Product(id = "6", title = "Йогурт Danio", calories = 109, isFavorites = false),
        Product(id = "7", title = "Йогурт Fruvita", calories = 87, isFavorites = false),
        Product(id = "8", title = "Капуста квашенная", calories = 19, isFavorites = false),
        Product(id = "9", title = "Капуста свежая 🥬", calories = 28, isFavorites = true),
        Product(id = "10", title = "Картофель вареный", calories = 76, isFavorites = false),
        Product(id = "11", title = "Колбаса вареная, сосиски", calories = 224, isFavorites = false),
        Product(id = "12", title = "Конфеты", calories = 460, isFavorites = false),
        Product(id = "13", title = "Куриная отбивная", calories = 168, isFavorites = false),
        Product(id = "14", title = "Курица с грибами", calories = 90, isFavorites = false),
        Product(id = "15", title = "Огурец", calories = 15, isFavorites = false),
        Product(id = "16", title = "Огурец квашеный", calories = 11, isFavorites = false),
        Product(id = "17", title = "Окорок жареный", calories = 195, isFavorites = false),
        Product(id = "18", title = "Олия", calories = 899, isFavorites = false),
        Product(id = "19", title = "Орех грецкий", calories = 680, isFavorites = false),
        Product(id = "20", title = "Помидор", calories = 20, isFavorites = false),
        Product(id = "21", title = "Сыр твердый 🧀", calories = 360, isFavorites = true),
        Product(id = "22", title = "Хлеб", calories = 266, isFavorites = false),
        Product(id = "23", title = "Яблоки сушеные", calories = 250, isFavorites = false),
        Product(id = "24", title = "Яблоко 🍏🍎", calories = 52, isFavorites = true),
        Product(id = "25", title = "Яйцо вареное 🥚", calories = 160, isFavorites = true),
        Product(id = "26", title = "Крекер", calories = 420, isFavorites = false),
        Product(id = "27", title = "Сметана", calories = 186, isFavorites = false),
        Product(id = "28", title = "Творожная запеканка", calories = 285, isFavorites = false),
        Product(id = "29", title = "Тунец консервы", calories = 180, isFavorites = false),
        Product(id = "30", title = "Борщ", calories = 58, isFavorites = false),
        Product(id = "31", title = "Оливье", calories = 190, isFavorites = false),
        Product(id = "32", title = "Слива сушёная", calories = 240, isFavorites = false),
        Product(id = "33", title = "Перец сладкий", calories = 21, isFavorites = false),
        Product(id = "34", title = "Творог 18%", calories = 236, isFavorites = false),
        Product(id = "35", title = "Пряник", calories = 355, isFavorites = false),
        Product(id = "36", title = "Вареники с картошкой", calories = 200, isFavorites = false),
        Product(id = "37", title = "Вареники с капустой", calories = 157, isFavorites = false),
        Product(id = "38", title = "Пиво Lech", calories = 39, isFavorites = false),
        Product(id = "39", title = "Чипсы", calories = 476, isFavorites = false),
        Product(id = "40", title = "Йогурт греческий 3%", calories = 70, isFavorites = false),
        Product(id = "41", title = "Яичница", calories = 176, isFavorites = false),
        Product(id = "42", title = "Ветчина", calories = 145, isFavorites = false),
        Product(id = "43", title = "Зефир", calories = 300, isFavorites = false),
        Product(id = "44", title = "Шашлык", calories = 218, isFavorites = false),
        Product(id = "45", title = "Картофель жареный", calories = 185, isFavorites = false),
        Product(id = "46", title = "Окрошка", calories = 280, isFavorites = false),
        Product(id = "47", title = "Суп", calories = 50, isFavorites = false),
        Product(id = "48", title = "Свинина с грибами", calories = 185, isFavorites = false),
        Product(id = "49", title = "Перловка вареная", calories = 74, isFavorites = false),
        Product(id = "50", title = "Макароны вареные", calories = 112, isFavorites = false),
        Product(id = "51", title = "Фарш с томатной пастой", calories = 72, isFavorites = false),
        Product(id = "52", title = "Морковь", calories = 42, isFavorites = false),
        Product(id = "53", title = "Пицца", calories = 266, isFavorites = false),
        Product(id = "54", title = "Йогурт Pilos", calories = 96, isFavorites = false),
        Product(id = "55", title = "Котлета", calories = 108, isFavorites = false),
        Product(id = "56", title = "Кетчуп", calories = 97, isFavorites = false),
        Product(id = "57", title = "Блины", calories = 200, isFavorites = false),
        Product(id = "58", title = "Кукуруза консервированная", calories = 77, isFavorites = false)
    )
}